# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: Build the TypeScript source
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies
COPY package*.json tsconfig.json ./
RUN npm install

# Copy source and build
COPY src ./src
RUN npm run build

# Ensure non-root ownership and set non-root user for builder stage
RUN chown -R node:node /app
USER node

# Stage 2: Create production image
FROM node:lts-alpine
WORKDIR /app

# Install only production dependencies
COPY package*.json ./
RUN npm install --only=production

# Copy built artifacts
COPY --from=builder /app/build ./build

# Ensure non-root ownership of app files
RUN chown -R node:node /app

# Default environment variables
ENV SERPAPI_API_KEY=a33a143758565da0ab6378366dc91138fe3fbfc1a2142e526c57a38882f9b2a6
ENV PORT=8107

# Expose port for SSE mode
EXPOSE 8107

# Start the MCP server (default: stdio mode, use --sse for SSE mode)
USER node
ENTRYPOINT ["node", "build/index.js"]
CMD []
